CREATE TABLE FINANCIAL
(
    ID           NUMBER PRIMARY KEY,
    AMOUNT       NUMBER,
    F_TYPE       NVARCHAR2(8),
    DATE_TIME    TIMESTAMP,
    DESCRIPTION  NVARCHAR2(100)
);



CREATE SEQUENCE FINANCIAL_SEQ START WITH 1 INCREMENT BY 1;